version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
stack_name = "cloudwatch-to-chat"
s3_prefix = "cloudwatch-to-chat"
