---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: &DESC Transfer Cloudwatch Alarms to Google Chat
Parameters:
  ChatWebhookUrl:
    Type: String
  OkImageUrl:
    Type: String
  AlertImageUrl:
    Type: String
  SnsArn:
    Type: String
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: .
      FunctionName: !Join ['-', [!Ref AWS::StackName, lambda]]
      Description: *DESC
      Timeout: 30
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          CHAT_WEBHOOK: !Ref ChatWebhookUrl
          OK_IMAGE_URL: !Ref OkImageUrl
          ALERT_IMAGE_URL: !Ref AlertImageUrl
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref SnsArn
            SqsSubscription: False
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/aws/lambda/, !Ref Function]]
      RetentionInDays: '7'
Outputs:
  Arn:
    Description: Function
    Value: !Ref Function
